name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: nimbasms-linux-amd64
            pyinstaller_args: --add-data "src:src"
          - os: macos-latest
            asset_name: nimbasms-darwin-amd64
            pyinstaller_args: --add-data "src:src"
          - os: windows-latest
            asset_name: nimbasms-windows-amd64.exe
            pyinstaller_args: --add-data "src;src"

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build binary
        run: |
          poetry run pip install pyinstaller
          poetry run pyinstaller src/cli.py --clean --onefile ${{ matrix.pyinstaller_args }} --name ${{ matrix.asset_name }}
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: dist/${{ matrix.asset_name }}*

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nimbasms-linux-amd64/nimbasms-linux-amd64
            nimbasms-darwin-amd64/nimbasms-darwin-amd64
            nimbasms-windows-amd64.exe/nimbasms-windows-amd64.exe
          draft: false
          prerelease: false
          generate_release_notes: true