name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build (${{ matrix.os }} - ${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            asset_name: nimbasms-linux-amd64
            build_tool: cxfreeze
          - os: macos-latest
            arch: amd64
            asset_name: nimbasms-darwin-amd64
            build_tool: cxfreeze
          - os: macos-latest
            arch: arm64
            asset_name: nimbasms-darwin-arm64
            build_tool: cxfreeze
          - os: windows-latest
            arch: amd64
            asset_name: nimbasms-windows-amd64.exe
            build_tool: cxfreeze

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build with cx_Freeze
        run: |
          poetry run pip install cx-Freeze
          poetry run cxfreeze src/cli.py --target-dir dist

      - name: Rename built files
        run: |
          mv dist/cli ${{ matrix.asset_name }} || mv dist/cli.exe ${{ matrix.asset_name }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: dist/${{ matrix.asset_name }}
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Prepare binaries for release
        run: |
          chmod +x dist/nimbasms-linux-amd64 || true
          chmod +x dist/nimbasms-darwin-amd64 || true
          chmod +x dist/nimbasms-darwin-arm64 || true
          chmod +x dist/nimbasms-windows-amd64.exe || true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            dist/nimbasms-linux-amd64
            dist/nimbasms-darwin-amd64
            dist/nimbasms-darwin-arm64
            dist/nimbasms-windows-amd64.exe